import { defineConfig } from "vite";
import { execSync } from "child_process";
import fs from "fs";
import path from "path";

function getVersionInfo() {
  try {
    let branch = execSync("git rev-parse --abbrev-ref HEAD").toString().trim();
    let hash = execSync("git describe --always --dirty").toString().trim();
    let build = execSync("git rev-list --count HEAD").toString().trim();
    const date = Math.floor(Date.now() / 1000);

    if (process.env.WERCKER_GIT_BRANCH) {
      branch = process.env.WERCKER_GIT_BRANCH;
      hash = hash.replace("-dirty", "");
    }

    return { branch, hash, build, date };
  } catch (err) {
    console.warn("⚠️ Version info unavailable:", err.message);
    return {
      branch: "unknown",
      hash: "unknown",
      build: "0",
      date: Math.floor(Date.now() / 1000),
    };
  }
}

function writeVersionFile(outDir) {
  const version = getVersionInfo();
  const content = `// Auto-generated by Vite build
export const date = ${version.date};
export const branch = "${version.branch}";
export const hash = "${version.hash}";
export const build = ${version.build};
export const version = \`\${branch}/\${hash}\`;
`;
  const filePath = path.join(outDir, "version.js");
  fs.writeFileSync(filePath, content);
  console.log(`✅ Wrote version.js to: ${filePath}`);
}

export default defineConfig({
  build: {
    lib: {
      entry: "framer/Framer.js",
      name: "Framer",
      fileName: "framer",
      // just one JS file
    },
    sourcemap: true,
    rollupOptions: {
      plugins: [
        {
          name: "generate-version-file",
          writeBundle(options) {
            // Runs after Vite finishes bundling
            writeVersionFile(options.dir || "dist");
          },
        },
      ],
    },
  },
  test: {
    globals: true,
    environment: "jsdom",
    setupFiles: "test/setup.js", // <-- include your new test bootstrap
    include: ["test/**/*.test.js"],
    coverage: {
      provider: "v8",
      reporter: ["text", "html"],
      reportsDirectory: "./coverage",
    },
  },
});
