import { _ } from "./Underscore.js";
import Utils from "./Utils.js";
import { Color } from "./Color.js";
import { Gradient } from "./Gradient.js";
import { Layer } from "./Layer.js";
import { BackgroundLayer } from "./BackgroundLayer.js";
import { VideoLayer } from "./VideoLayer.js";
import { SVGLayer } from "./SVGLayer.js";
import { SVGPath } from "./SVGPath.js";
import { SVGGroup } from "./SVGGroup.js";
import { TextLayer } from "./TextLayer.js";
import { Events } from "./Events.js";
import { Gestures } from "./Gestures.js";
import { Animation } from "./Animation.js";
import { AnimationGroup, AnimationStateGroup } from "./AnimationGroup.js";
import { Screen } from "./Screen.js";
import { Align } from "./Align.js";
import { Blending } from "./Blending.js";
import { print } from "./Print.js";

import { ScrollComponent } from "./Components/ScrollComponent.js";
import { PageComponent } from "./Components/PageComponent.js";
import { SliderComponent } from "./Components/SliderComponent.js";
import { RangeSliderComponent } from "./Components/RangeSliderComponent.js";
import { DeviceComponent } from "./Components/DeviceComponent.js";
import { GridComponent } from "./Components/GridComponent.js";
import { FlowComponent } from "./Components/FlowComponent.js";
import { CircularProgressComponent } from "./Components/CircularProgressComponent.js";
import { MIDIComponent } from "./Components/MIDIComponent.js";

import { Context } from "./Context.js";
import { Config } from "./Config.js";
import { EventEmitter } from "./EventEmitter.js";
import { BaseClass } from "./BaseClass.js";
import { LayerStyle } from "./LayerStyle.js";
import { AnimationLoop } from "./AnimationLoop.js";
import { LinearAnimator } from "./Animators/LinearAnimator.js";
import { BezierCurveAnimator } from "./Animators/BezierCurveAnimator.js";
import { SpringDHOAnimator } from "./Animators/SpringDHOAnimator.js";
import { SpringRK4Animator } from "./Animators/SpringRK4Animator.js";
import * as Curves from "./Animators/Curves.js";
import { Importer } from "./Importer.js";
import * as Extras from "./Extras/Extras.js";
import { GestureInputRecognizer } from "./GestureInputRecognizer.js";
import { Defaults } from "./Defaults.js";
import { Canvas } from "./Canvas.js";

// Import version file generated by Vite build
import * as Version from "./version.js";

const Framer = {};

// Root modules
Framer._ = _;
Framer.Utils = Utils;
Framer.Color = Color;
Framer.Gradient = Gradient;
Framer.Layer = Layer;
Framer._Layer = Layer;
Framer.BackgroundLayer = BackgroundLayer;
Framer.VideoLayer = VideoLayer;
Framer.SVGLayer = SVGLayer;
Framer.SVGPath = SVGPath;
Framer.SVGGroup = SVGGroup;
Framer.TextLayer = TextLayer;
Framer.Events = Events;
Framer.Gestures = Gestures;
Framer.Animation = Animation;
Framer.AnimationGroup = AnimationGroup;
Framer.AnimationStateGroup = AnimationStateGroup;
Framer.Screen = Screen;
Framer.Align = Align;
Framer.Blending = Blending;
Framer.print = print;

// Components
Framer.ScrollComponent = ScrollComponent;
Framer.PageComponent = PageComponent;
Framer.SliderComponent = SliderComponent;
Framer.RangeSliderComponent = RangeSliderComponent;
Framer.DeviceComponent = DeviceComponent;
Framer.DeviceView = DeviceComponent;
Framer.GridComponent = GridComponent;
Framer.FlowComponent = FlowComponent;
Framer.CircularProgressComponent = CircularProgressComponent;
Framer.MIDIComponent = MIDIComponent;

// Framer level modules
Framer.Context = Context;
Framer.Config = Config;
Framer.EventEmitter = EventEmitter;
Framer.BaseClass = BaseClass;
Framer.LayerStyle = LayerStyle;
Framer.AnimationLoop = AnimationLoop;
Framer.LinearAnimator = LinearAnimator;
Framer.BezierCurveAnimator = BezierCurveAnimator;
Framer.SpringDHOAnimator = SpringDHOAnimator;
Framer.SpringRK4Animator = SpringRK4Animator;
Framer.LayerDraggable = Layer;

Framer.Curves = Curves;
if (typeof window !== "undefined") {
  window.Bezier = Curves.Bezier;
  window.Spring = Curves.Spring;
}

Framer.Importer = Importer;
Framer.Extras = Extras;

Framer.GestureInputRecognizer = new GestureInputRecognizer();
Framer.Version = Version;
Framer.Loop = new AnimationLoop();

// Metadata
Framer.Info = {};

// Attach to window safely
if (typeof window !== "undefined") {
  _.extend(window, Framer);
  window.Framer = Framer;
}

// Set defaults
Defaults.setup();
Framer.resetDefaults = Defaults.reset;

// Default context
Framer.DefaultContext = new Context({ name: "Default" });
Framer.DefaultContext.backgroundColor = "white";
Framer.CurrentContext = Framer.DefaultContext;

// Canvas
if (typeof window !== "undefined") {
  window.Canvas = new Canvas();
}

// Extras
if (Utils.isMobile()) Framer.Extras.MobileScrollFix.enable();
if (!Utils.isTouch()) Framer.Extras.TouchEmulator.enable();
if (!Utils.isFramerStudio()) Framer.Extras.ErrorDisplay.enable();
if (!Utils.isFramerStudio()) Framer.Extras.Preloader.enable();
if (!Utils.isFramerStudio()) Framer.Extras.Hints.enable();

Utils.domComplete(() => Framer.Loop.start());

export default Framer;
